### ISSUE TITLE
Algunas pequeñas erratas

### ISSUE THREAD

**Issue by 29antonioac** [libreim/AlgoritmosGeneticos#2]
Hola! No nos conocemos, soy de 4º del Doble Grado. He estado leyendo tus notas y me han venido muy bien :). Quería comentarte unas pequeñas erratas sin importancia. Creo que tengo acceso al repo pero prefiero avisarte para que tengas constancia de ello (sería raro ver un commit de alguien a quien no has visto en tu vida XD).

En la página 2, en la definición de "Ineligencia Artificial", falta la t.
En la página 7, en la sección "Problemas de optimización en Codificación Binaria", en el cruce por un punto, el vector hijo tiene el +1 fuera del subíndice.

Creo que no hay más, aunque si veo algo te aviso.

Gracias por redactar y compartir estas notas!

**Comment by andreshp** [comment]
Me alegro de que hayan sido de ayuda.

Gracias por localizar las erratas! Ya están actualizadas ^^

Un saludo!

**Comment by oxcar103** [comment]
Unas cuántas erratillas más(indico la línea del .Rmd):
1) Línea 39: "saber cual es mejor" sería "cuál", no?
2) Línea 240: "$$ v((x(1),x(2),...,x(n))) = \{(x(1),...,x(i-1),x(j),x(i+1),...,x(j-1),x(j+1),...,x(n)): i,j \in \{1,..,n\} \} $$" te falta el elemento x(i) que no sé si iría a la izquierda o la derecha de x(j)(por el ejemplo de la línea 243, deduzco que a la derecha)
3) Línea 471: "algoritmo genético desarrollado por mi" -> "mí"
¿4)? Línea 512: "incapié", según la RAE, lleva "h".

Nota:
Esto no es una errata pero bueno, en la línea 96, creo que el número de soluciones sería (n-1)!, siempre podemos fijar el nodo de partida y no se altera el resultado o he metido la pata?

**Comment by andreshp** [comment]
Arreglado ^^. Sí, es (n-1)! ;-)

Muchas gracias Óscar!
